// Promote only the already authenticated-tested canonical Worker. Never deploy the import/test wrapper.
import{readFileSync,writeFileSync,mkdirSync}from'node:fs';import{createHash}from'node:crypto';import{execFileSync}from'node:child_process';import assert from'node:assert/strict';
const script='coco-eterna-v159',production='https://coco-eterna-v159.chatinmobiliario.workers.dev',release='eterna-library-2026.09-v3-217-6b83',oldRelease='eterna-library-2026.09-v2-160-3069e276',expectedBase='616b2ff8-5a2c-43a8-9092-5d70a42f14e2';
const proof=JSON.parse(readFileSync('.private-proof/combined-private-evidence/report.json')),build=JSON.parse(readFileSync('.private-proof/combined-evidence/report.json'));
assert.equal(proof.phase,'canonical-private-verified');assert.equal(proof.release,release);assert.equal(proof.base_version,expectedBase);assert.equal(proof.requests.length,96);assert.equal(proof.synthetic_cleanup.ok,true);assert.equal(proof.synthetic_cleanup.deleted,true);assert.equal(proof.draft_content.lessons,217);assert.equal(proof.draft_content.protocols,56);assert.equal(proof.draft_content.hash_mismatches,0);assert.equal(build.tests_failed,0);assert.equal(proof.regressions_passed,build.tests_passed);assert.ok(build.tests_passed>=500);assert.equal(proof.ui_scenarios,42);assert.equal(build.ui_model_calls,0);assert.equal(build.base_160_preserved,true);
for(const r of proof.requests){assert.equal(r.generation_model_calls,0);assert.equal(r.generation_tokens,0)}
const hash=x=>createHash('sha256').update(x).digest('hex');for(const[path,p]of Object.entries(proof.source_hashes))assert.equal(hash(readFileSync(path)),p.sha256,'Different release bytes: '+path);
const source=readFileSync('eterna-worker/src/index.js','utf8');assert.ok(!source.includes('__synthetic_library_qa'));assert.equal(hash(source.replaceAll(release,oldRelease)),'fea7fcf5085200f8472eb83a340b774f8e0ba017160a6bf9d0f57e3ad0698ae4','Unrelated Worker integration changed');
const expectedMain=String(process.env.EXPECTED_MAIN||'');assert.match(expectedMain,/^[a-f0-9]{40}$/);assert.equal(execFileSync('git',['rev-parse','HEAD:eterna-worker/src/index.js'],{encoding:'utf8'}).trim(),proof.source_hashes['eterna-worker/src/index.js'].sha);
const token=String(process.env.CLOUDFLARE_API_TOKEN||'').replace(/\s/g,''),account=String(process.env.CLOUDFLARE_ACCOUNT_INPUT||'').replace(/^https:\/\/dash.cloudflare.com\//,'').split('/')[0];assert.ok(token&&/^[a-f0-9]{32}$/i.test(account));console.log('::add-mask::'+token);console.log('::add-mask::'+account);
async function mainHead(){const r=await fetch('https://api.github.com/repos/diegopenn-png/coco-en-forma/git/ref/heads/main',{headers:{Authorization:'Bearer '+process.env.GH_TOKEN,Accept:'application/vnd.github+json'},signal:AbortSignal.timeout(25000)});assert.equal(r.status,200);return(await r.json()).object.sha}
async function cf(path){const r=await fetch(`https://api.cloudflare.com/client/v4/accounts/${account}/workers/scripts/${script}${path}`,{headers:{Authorization:'Bearer '+token},signal:AbortSignal.timeout(30000)});const p=await r.json();assert.ok(r.ok&&p.success!==false,'Cloudflare read failed '+r.status);return p.result}
async function live(){const p=await cf('/deployments'),d=(Array.isArray(p)?p:p.deployments)?.[0];assert.ok(d?.versions?.length===1&&d.versions[0].percentage===100,'Expected one production version');return d}
function canon(v){return Array.isArray(v)?v.map(canon):v&&typeof v==='object'?Object.fromEntries(Object.keys(v).sort().map(k=>[k,canon(v[k])])):v}
const fingerprint=v=>hash(JSON.stringify(canon(v)));const bindings=v=>v.resources.bindings.filter(b=>b.name!=='ETERNA_LIBRARY_RELEASE').sort((a,b)=>a.name.localeCompare(b.name));
const baseline=await live();assert.equal(baseline.versions[0].version_id,expectedBase,'Concurrent deployment; stop');assert.equal(await mainHead(),expectedMain);
const old=await cf('/versions/'+expectedBase),candidate=await cf('/versions/'+proof.candidate_version);
assert.equal(old.resources.script.etag,proof.base_code_etag);assert.equal(candidate.resources.script.etag,proof.candidate_code_etag);assert.equal(fingerprint(bindings(candidate)),fingerprint(bindings(old)),'Unrelated bindings changed');assert.equal(fingerprint(candidate.resources.script_runtime),fingerprint(old.resources.script_runtime),'Runtime changed');
const vars=Object.fromEntries(candidate.resources.bindings.filter(b=>b.type==='plain_text').map(b=>[b.name,b.text]));assert.equal(vars.ENABLE_ETERNA_LIBRARY,'true');assert.equal(vars.ETERNA_LIBRARY_RELEASE,release);
async function health(url,newVersion){const r=await fetch(url+'/health',{signal:AbortSignal.timeout(20000)});assert.equal(r.status,200);const p=await r.json();assert.equal(p.ok,true);assert.equal(p.owned_library?.enabled,true);assert.equal(p.owned_library.release,newVersion?release:oldRelease);assert.equal(p.owned_library.lessons,newVersion?217:160);assert.equal(p.owned_library.protocols,newVersion?56:40);assert.equal(p.owned_library.curriculum_complete,false);return p}
const configFingerprint=p=>fingerprint({provider:p.ai_provider,models:p.model_configuration,features:p.features,supabase:p.supabase_configured,stripe:p.stripe_configured,openai:p.openai_configured,cloudflare:p.cloudflare_ai_configured});
async function denied(url){for(const path of ['/v1/chat','/v1/chat-job','/v1/transcribe']){const r=await fetch(url+path,{method:'POST',headers:{Origin:'https://cocoenforma.com'},signal:AbortSignal.timeout(20000)});assert.equal(r.status,401,'Unauthorized route no longer blocked '+path)}}
const oldHealth=await health(production,false),candidateHealth=await health(proof.candidate_url,true);assert.equal(configFingerprint(oldHealth),configFingerprint(candidateHealth));await denied(production);await denied(proof.candidate_url);
for(const b of candidate.resources.bindings)assert.ok(['plain_text','secret_text','ai'].includes(b.type),'Unmapped binding');
const rt=candidate.resources.script_runtime||{},ai=candidate.resources.bindings.find(b=>b.type==='ai'),config={name:script,main:'src/index.js',compatibility_date:rt.compatibility_date,compatibility_flags:rt.compatibility_flags||[],vars};if(ai)config.ai={binding:ai.name};if(rt.limits?.cpu_ms)config.limits={cpu_ms:rt.limits.cpu_ms};
writeFileSync('eterna-worker/.library-combined-production.json',JSON.stringify(config));mkdirSync('combined-production-evidence',{recursive:true});
const report={phase:'pre-promotion',release,production_commit:expectedMain,base_version:expectedBase,candidate_version:proof.candidate_version,source_sha256:proof.source_sha256,runtime_sha256:proof.runtime_sha256,content_sha256:proof.source_hashes['eterna-worker/src/library/content-v1.js'].sha256,lessons:217,added_over_prior_160:57,questions:651,protocols:56,new_protocols:16,base_160_preserved:true,alternatives_not_activated:23,tests_passed:build.tests_passed,ui_scenarios:42,real_authenticated_private_requests:96,private_latency:proof.latency,private_zero_generation_tokens:true,temporary_identity_deleted:true,models_unchanged:true,unrelated_bindings_unchanged:true,runtime_unchanged:true,microphone_unchanged:true,frontend_unchanged:true,production_changed:false,full_curriculum_complete:false,human_teacher_reviewed:false};
const save=()=>writeFileSync('combined-production-evidence/report.json',JSON.stringify(report,null,2));save();
function deploy(id,message){try{execFileSync('npx',['wrangler','versions','deploy',id+'@100%','--name',script,'--config','.library-combined-production.json','--message',message,'--yes'],{cwd:'eterna-worker',env:{...process.env,CLOUDFLARE_API_TOKEN:token,CLOUDFLARE_ACCOUNT_ID:account,CI:'true'},encoding:'utf8',timeout:180000,maxBuffer:8*1024*1024})}catch(e){throw Error('Controlled deployment failed '+e.status+'; confidential output omitted')}}
assert.equal((await live()).id,baseline.id);assert.equal(await mainHead(),expectedMain);let attempted=false;
try{
 attempted=true;deploy(proof.candidate_version,'Activate immutable verified 217-lesson / 56-protocol library; all prior content and voice retained');let current,passed=false;
 for(let i=0;i<6;i++){current=await live();if(current.versions[0].version_id===proof.candidate_version){try{assert.equal(configFingerprint(await health(production,true)),configFingerprint(oldHealth));await denied(production);passed=true;break}catch{}}await new Promise(r=>setTimeout(r,5000))}
 assert.ok(passed,'Production verification failed');assert.equal(await mainHead(),expectedMain);report.phase='production-verified';report.production_changed=true;report.production_version=proof.candidate_version;report.deployment_id=current.id;report.verified_at=new Date().toISOString();save();console.log(JSON.stringify(report));
}catch(e){report.phase='not-ready';report.error=String(e.message).slice(0,300);if(attempted){const current=await live();if(current.versions[0].version_id===proof.candidate_version){deploy(expectedBase,'Rollback failed consolidated library promotion');report.rollback_verified=(await live()).versions[0].version_id===expectedBase}else report.rollback_skipped_concurrent_change=true}save();throw e}
