// Promote the immutable canonical Worker already tested with actual auth. Never publish QA wrappers.
import{readFileSync,writeFileSync,mkdirSync}from'node:fs';import{createHash}from'node:crypto';import{execFileSync}from'node:child_process';import assert from'node:assert/strict';
const script='coco-eterna-v159',production='https://coco-eterna-v159.chatinmobiliario.workers.dev',release='eterna-library-2026.09-v5-304-panel-ffe822',oldRelease='eterna-library-2026.09-v4-256-reviewed-c993',baseVersion='6181ec9c-d5be-44f1-a9a2-f7390fbfd73b',expectedMain='12c672a4e67646f8da3bba125ccdaade7e34d7a0';
const proof=JSON.parse(readFileSync('.private-proof/report.json')),build=JSON.parse(readFileSync('.build-proof/report.json'));
assert.equal(proof.phase,'canonical-private-verified');assert.equal(proof.release,release);assert.equal(proof.base_version,baseVersion);assert.equal(proof.candidate_version,'ce846fe8-2f9a-4c4e-ba72-397dcc14e2db');assert.equal(proof.requests.length,96);assert.equal(proof.synthetic_cleanup.ok,true);assert.equal(proof.synthetic_cleanup.deleted,true);assert.equal(proof.draft_content.lessons,304);assert.equal(proof.draft_content.protocols,56);assert.equal(proof.draft_content.hash_mismatches,0);assert.equal(build.tests_failed,0);assert.equal(build.tests_passed,674);assert.equal(proof.regressions_passed,674);assert.equal(proof.simulated_panel,true);assert.equal(proof.human_teacher_reviewed,false);assert.equal(proof.ui_scenarios_newly_tested,0);
for(const r of proof.requests){assert.equal(r.generation_model_calls,0);assert.equal(r.generation_tokens,0)}
const hash=v=>createHash('sha256').update(v).digest('hex');for(const[path,p]of Object.entries(proof.source_hashes))assert.equal(hash(readFileSync(path)),p.sha256,'Unverified source '+path);
const source=readFileSync('eterna-worker/src/index.js','utf8'),runtime=readFileSync('eterna-worker/src/library/runtime-v1.js','utf8');
assert.equal(hash(source.replaceAll(release,oldRelease)),'e44de7bb8233758d3141198832abc6fc67f4a92e75ae633b95e5e55c78240623');
assert.equal(hash(runtime.replaceAll(release,oldRelease).replace("const VERSION='library-first-v5-panel';","const VERSION='library-first-v4-reviewed';")),'441bbdb5b2f87c50535f9a7113976b4af873f315067ffbd24c68815d2a01d2c3');
assert.ok(!source.includes('__synthetic_library_qa'));assert.equal(execFileSync('git',['rev-parse','HEAD:eterna-worker/src/index.js'],{encoding:'utf8'}).trim(),proof.source_hashes['eterna-worker/src/index.js'].sha);
const token=String(process.env.CLOUDFLARE_API_TOKEN||'').replace(/\s/g,''),account=String(process.env.CLOUDFLARE_ACCOUNT_INPUT||'').replace(/^https:\/\/dash.cloudflare.com\//,'').split('/')[0];assert.ok(token&&/^[a-f0-9]{32}$/i.test(account));console.log('::add-mask::'+token);console.log('::add-mask::'+account);
async function main(){const r=await fetch('https://api.github.com/repos/diegopenn-png/coco-en-forma/git/ref/heads/main',{headers:{Authorization:'Bearer '+process.env.GH_TOKEN,Accept:'application/vnd.github+json'},signal:AbortSignal.timeout(25000)});assert.equal(r.status,200);return(await r.json()).object.sha}
async function cf(path){const r=await fetch(`https://api.cloudflare.com/client/v4/accounts/${account}/workers/scripts/${script}${path}`,{headers:{Authorization:'Bearer '+token},signal:AbortSignal.timeout(30000)});const p=await r.json();assert.ok(r.ok&&p.success!==false,'Cloudflare control read failed '+r.status);return p.result}
async function live(){const p=await cf('/deployments'),d=(Array.isArray(p)?p:p.deployments)?.[0];assert.ok(d?.versions?.length===1&&d.versions[0].percentage===100);return d}
function canon(v){return Array.isArray(v)?v.map(canon):v&&typeof v==='object'?Object.fromEntries(Object.keys(v).sort().map(k=>[k,canon(v[k])])):v}
const fp=v=>hash(JSON.stringify(canon(v))),bindings=v=>v.resources.bindings.filter(b=>b.name!=='ETERNA_LIBRARY_RELEASE').sort((a,b)=>a.name.localeCompare(b.name));
const baseline=await live();assert.equal(baseline.versions[0].version_id,baseVersion,'Production changed; stop');assert.equal(await main(),expectedMain,'Main changed; stop');
const old=await cf('/versions/'+baseVersion),candidate=await cf('/versions/'+proof.candidate_version);
assert.equal(old.resources.script.etag,proof.base_code_etag);assert.equal(candidate.resources.script.etag,proof.candidate_code_etag);assert.equal(fp(bindings(old)),fp(bindings(candidate)));assert.equal(fp(old.resources.script_runtime),fp(candidate.resources.script_runtime));
const vars=Object.fromEntries(candidate.resources.bindings.filter(b=>b.type==='plain_text').map(b=>[b.name,b.text]));assert.equal(vars.ENABLE_ETERNA_LIBRARY,'true');assert.equal(vars.ETERNA_LIBRARY_RELEASE,release);
async function health(url,isNew){const r=await fetch(url+'/health',{signal:AbortSignal.timeout(20000),headers:{'Cache-Control':'no-cache'}});assert.equal(r.status,200);const p=await r.json();assert.equal(p.ok,true);assert.equal(p.owned_library?.enabled,true);assert.equal(p.owned_library.release,isNew?release:oldRelease);assert.equal(p.owned_library.lessons,isNew?304:256);assert.equal(p.owned_library.protocols,56);assert.equal(p.owned_library.curriculum_complete,false);return p}
const settings=p=>fp({provider:p.ai_provider,models:p.model_configuration,features:p.features,supabase:p.supabase_configured,stripe:p.stripe_configured,openai:p.openai_configured,cloudflare:p.cloudflare_ai_configured});
async function denied(url){for(const path of ['/v1/chat','/v1/chat-job','/v1/transcribe']){const r=await fetch(url+path,{method:'POST',headers:{Origin:'https://cocoenforma.com'},signal:AbortSignal.timeout(20000)});assert.equal(r.status,401,path+' lost authentication gate')}}
const oldHealth=await health(production,false);assert.equal(settings(await health(proof.candidate_url,true)),settings(oldHealth));await denied(production);await denied(proof.candidate_url);
for(const b of candidate.resources.bindings)assert.ok(['plain_text','secret_text','ai'].includes(b.type));
const rt=candidate.resources.script_runtime||{},ai=candidate.resources.bindings.find(b=>b.type==='ai'),config={name:script,main:'src/index.js',compatibility_date:rt.compatibility_date,compatibility_flags:rt.compatibility_flags||[],vars};if(ai)config.ai={binding:ai.name};if(rt.limits?.cpu_ms)config.limits={cpu_ms:rt.limits.cpu_ms};
writeFileSync('eterna-worker/.panel-production.json',JSON.stringify(config));mkdirSync('panel-production-evidence',{recursive:true});
const report={phase:'pre-promotion',release,production_commit:expectedMain,base_version:baseVersion,candidate_version:proof.candidate_version,source_sha256:proof.source_sha256,runtime_sha256:proof.runtime_sha256,content_sha256:proof.source_hashes['eterna-worker/src/library/content-v1.js'].sha256,lessons:304,questions:912,protocols:56,added_lessons:48,tests_passed:674,real_authenticated_private_requests:96,private_latency:proof.latency,private_zero_generation_tokens:true,synthetic_identity_deleted:true,simulated_panel:true,human_teacher_reviewed:false,review_ledger_items:304,full_curriculum_complete:false,ui_scenarios_newly_tested:0,models_unchanged:true,bindings_unchanged_except_release:true,runtime_configuration_unchanged:true,runtime_algorithm_unchanged:true,microphone_unchanged:true,frontend_unchanged:true,production_changed:false};
const save=()=>writeFileSync('panel-production-evidence/report.json',JSON.stringify(report,null,2));save();
function deploy(id,msg){try{execFileSync('npx',['wrangler','versions','deploy',id+'@100%','--name',script,'--config','.panel-production.json','--message',msg,'--yes'],{cwd:'eterna-worker',encoding:'utf8',timeout:180000,maxBuffer:8*1024*1024,env:{...process.env,CLOUDFLARE_API_TOKEN:token,CLOUDFLARE_ACCOUNT_ID:account,CI:'true'}})}catch(e){throw Error('Controlled deployment failed '+e.status+'; confidential output omitted')}}
assert.equal((await live()).id,baseline.id);assert.equal(await main(),expectedMain);let attempted=false;
try{
 attempted=true;deploy(proof.candidate_version,'Activate exact tested 304-lesson simulated-panel content; preserve voice, state and all models');let current,ok=false;
 for(let i=0;i<6;i++){current=await live();if(current.versions[0].version_id===proof.candidate_version){try{assert.equal(settings(await health(production,true)),settings(oldHealth));await denied(production);ok=true;break}catch{}}await new Promise(r=>setTimeout(r,5000))}
 assert.ok(ok,'Post-promotion verification failed');assert.equal(await main(),expectedMain);report.phase='production-verified';report.production_changed=true;report.production_version=proof.candidate_version;report.deployment_id=current.id;report.verified_at=new Date().toISOString();save();console.log(JSON.stringify(report));
}catch(e){report.phase='not-ready';report.error=String(e.message).slice(0,300);if(attempted){const current=await live();if(current.versions[0].version_id===proof.candidate_version){deploy(baseVersion,'Rollback failed panel content promotion');report.rollback_verified=(await live()).versions[0].version_id===baseVersion}else report.rollback_skipped_concurrent_change=true}save();throw e}
