-- ETERNA v159 · SEMILLA CURRICULAR DE PRUEBA
-- NO sustituye el corpus estatal/autonómico completo. Sirve para validar retrieval + tutor + verificador.
-- Requiere haber ejecutado supabase-eterna-v159.sql.
with src as (select id,stage from public.eterna_curriculum_sources where jurisdiction='ES-STATE')
insert into public.eterna_concepts(source_id,jurisdiction,stage,school_year,subject,concept_code,title,summary,prerequisites,verification_notes)
values
((select id from src where stage='primaria' limit 1),'ES-STATE','primaria','3º de Primaria','Matemáticas','MAT-P3-MULT','Multiplicación','Interpretar y calcular multiplicaciones sencillas, conectándolas con suma repetida y situaciones cotidianas.','["suma","conteo"]','Semilla de validación; revisar contra concreción autonómica.'),
((select id from src where stage='primaria' limit 1),'ES-STATE','primaria','4º de Primaria','Matemáticas','MAT-P4-DIV','División','Comprender el reparto y agrupamiento y resolver divisiones acordes al nivel.','["multiplicación","resta"]','Semilla de validación; revisar contra concreción autonómica.'),
((select id from src where stage='primaria' limit 1),'ES-STATE','primaria','5º de Primaria','Matemáticas','MAT-P5-FRAC-EQ','Fracciones equivalentes','Reconocer y producir fracciones equivalentes usando representaciones y relaciones multiplicativas.','["fracción como parte de un todo","multiplicación","división"]','Semilla de validación; revisar contra concreción autonómica.'),
((select id from src where stage='primaria' limit 1),'ES-STATE','primaria','6º de Primaria','Matemáticas','MAT-P6-PORC','Porcentajes','Relacionar fracciones, decimales y porcentajes en situaciones sencillas y resolver porcentajes básicos.','["fracciones","decimales","multiplicación"]','Semilla de validación.'),
((select id from src where stage='primaria' limit 1),'ES-STATE','primaria','5º de Primaria','Lengua Castellana y Literatura','LEN-P5-COMP','Comprensión lectora','Localizar información explícita, realizar inferencias sencillas y justificar respuestas a partir de un texto.','[]','Semilla de validación.'),
((select id from src where stage='primaria' limit 1),'ES-STATE','primaria','5º de Primaria','Conocimiento del Medio','CM-P5-FOTO','Fotosíntesis','Comprender de forma escolar cómo las plantas producen materia orgánica usando luz, agua y dióxido de carbono y liberan oxígeno.','["partes de la planta"]','Semilla de validación.'),
((select id from src where stage='primaria' limit 1),'ES-STATE','primaria','4º de Primaria','Conocimiento del Medio','CM-P4-AGUA','Ciclo del agua','Reconocer evaporación, condensación, precipitación e infiltración dentro del ciclo del agua.','["estados del agua"]','Semilla de validación.'),
((select id from src where stage='primaria' limit 1),'ES-STATE','primaria','5º de Primaria','Lengua Extranjera - Inglés','ENG-P5-PAST','Past simple básico','Comprender y producir estructuras sencillas en pasado con verbos frecuentes, distinguiendo regulares e irregulares habituales.','["present simple","verb to be"]','Semilla de validación.'),
((select id from src where stage='eso' limit 1),'ES-STATE','eso','1º de ESO','Matemáticas','MAT-E1-ENTEROS','Números enteros','Operar y razonar con números enteros en contextos numéricos y cotidianos.','["números naturales"]','Semilla de validación.'),
((select id from src where stage='eso' limit 1),'ES-STATE','eso','2º de ESO','Matemáticas','MAT-E2-EC1','Ecuaciones de primer grado','Modelizar y resolver ecuaciones lineales sencillas comprobando la solución.','["operaciones con enteros","propiedad distributiva"]','Semilla de validación.'),
((select id from src where stage='eso' limit 1),'ES-STATE','eso','1º de ESO','Biología y Geología','BIO-E1-CEL','La célula','Identificar la célula como unidad básica y reconocer estructuras fundamentales de células animales y vegetales.','[]','Semilla de validación.'),
((select id from src where stage='eso' limit 1),'ES-STATE','eso','2º de ESO','Geografía e Historia','GH-E2-MED','Edad Media','Situar procesos y conceptos principales de la Edad Media en un marco temporal y espacial básico.','[]','Semilla de validación; exigir fuente para detalle factual.'),
((select id from src where stage='bachillerato' limit 1),'ES-STATE','bachillerato','1º de Bachillerato','Matemáticas I','MAT-B1-FUNC','Funciones','Analizar propiedades básicas de funciones, representaciones y variación dentro del nivel.','["álgebra","coordenadas"]','Semilla de validación.'),
((select id from src where stage='bachillerato' limit 1),'ES-STATE','bachillerato','2º de Bachillerato','Historia de España','HES-B2-SXIX','España en el siglo XIX','Organizar procesos históricos españoles del siglo XIX atendiendo a cronología, causalidad y cambio.','[]','Semilla de validación; exigir fuentes para afirmaciones factuales.')
on conflict(jurisdiction,school_year,subject,concept_code) do update set summary=excluded.summary,updated_at=now();
