-- Coco en Forma v144.0
-- Migración aditiva y reversible. No modifica partidas, perfiles ni los datos históricos.
-- Ejecutar en Supabase SQL Editor después de realizar una copia de seguridad.

begin;

create table if not exists public.coco_runner_history (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  mission_id text not null check (char_length(mission_id) between 3 and 160),
  level smallint not null check (level between 1 and 3),
  play_date date not null,
  stats jsonb not null default '{}'::jsonb,
  completed_at timestamptz not null default now(),
  created_at timestamptz not null default now(),
  constraint coco_runner_one_daily_mission unique (user_id, play_date),
  constraint coco_runner_stats_object check (jsonb_typeof(stats) = 'object')
);

create index if not exists coco_runner_history_user_date_idx
  on public.coco_runner_history (user_id, play_date desc);

alter table public.coco_runner_history enable row level security;

do $$
begin
  if not exists (
    select 1 from pg_policies
    where schemaname = 'public' and tablename = 'coco_runner_history'
      and policyname = 'runner_select_own'
  ) then
    create policy runner_select_own on public.coco_runner_history
      for select to authenticated using (auth.uid() = user_id);
  end if;

  if not exists (
    select 1 from pg_policies
    where schemaname = 'public' and tablename = 'coco_runner_history'
      and policyname = 'runner_insert_own'
  ) then
    create policy runner_insert_own on public.coco_runner_history
      for insert to authenticated with check (auth.uid() = user_id);
  end if;
end
$$;

grant select, insert on public.coco_runner_history to authenticated;
grant usage, select on sequence public.coco_runner_history_id_seq to authenticated;

comment on table public.coco_runner_history is
  'Resultados personales de Coco Corre. No forma parte de partidas ni de ninguna clasificación.';

commit;

