/* Coco en Forma · Service Worker v160.100.1 · Relational continuity */
const CACHE_VERSION="coco-en-forma-v160.100.1-relational-continuity-r2";
const CACHE_PREFIX="coco-en-forma-";
const SCOPE_URL=new URL("./",self.registration.scope);
const INDEX_URL=new URL("index.html",SCOPE_URL).href;
const ETERNA_CORE_PATH="./eterna-v159.js";
const ETERNA_EXPERIENCE_PATH="./eterna-experience-v160.js";
const ETERNA_HOTFIX_PATH="./eterna-hotfix-v160902.js";
const ETERNA_DESKTOP_COMPACT_PATH="./eterna-desktop-compact-v160907.js";
const ETERNA_MIC_ONLY_PATH="./eterna-mic-only-v4.js";
const ETERNA_VOICE_AUTOCUT_PATH="./eterna-voice-autocut-v160907.js";
const PRODUCT_UX_PATH="./coco-release-v160903.js";
const RETO_2026_PATH="./coco-reto-2026-v160908.js";
const FAMILY_FRIENDLY_PATH="./coco-family-friendly-v160100.js";
const COCO_BOOTSTRAP_PATH="./coco-v153-fixes.js";
const SW_UA=String((self.navigator&&self.navigator.userAgent)||"");
const DESKTOP_SAFARI=/Safari\//.test(SW_UA)&&!/(Chrome|Chromium|CriOS|FxiOS|EdgiOS|OPR)\//.test(SW_UA)&&/Macintosh/.test(SW_UA)&&!/Mobile\//.test(SW_UA);
const CORE=["./index.html","./manifest.webmanifest","./manifest.json","./supabase-js-2.112.3.min.js","./coco-v142-content-extension.js","./coco-v142-runtime.js","./coco-variety-director-v160960.js","./coco-v142-unified.js","./coco-v144-content.js","./coco-v144-core.js","./coco-v152-pwa.js",COCO_BOOTSTRAP_PATH,"./coco-v155-identity.js",PRODUCT_UX_PATH,RETO_2026_PATH,FAMILY_FRIENDLY_PATH,"./coco-excellence-v160934.js","./eterna-state-contract-v3.js",ETERNA_CORE_PATH,"./eterna-v159.css",ETERNA_EXPERIENCE_PATH,ETERNA_HOTFIX_PATH,ETERNA_DESKTOP_COMPACT_PATH,ETERNA_MIC_ONLY_PATH,ETERNA_VOICE_AUTOCUT_PATH,"./eterna-marketing-attribution-v1.js","./coco-flex-eterna.jpg","./coco-v144-professional.css","./coco-v147-refinements.css","./coco-v149-refinements.css","./coco-v152-refinements.css","./coco-v153-release.css","./icon-192.png","./icon-512.png","./icon-maskable-192.png","./icon-maskable-512.png","./apple-touch-icon.png","./favicon.png"];
function absolute(p){return new URL(p,SCOPE_URL).href}
function releaseRequest(url){const fresh=new URL(url);fresh.searchParams.set("__coco_release",CACHE_VERSION);return new Request(fresh.href,{cache:"reload"})}
async function cacheCore(){const c=await caches.open(CACHE_VERSION);await Promise.allSettled(CORE.map(async p=>{const u=absolute(p);const r=await fetch(releaseRequest(u));if(r&&r.ok)await c.put(u,r.clone())}))}
self.addEventListener("install",e=>{e.waitUntil((async()=>{await cacheCore();self.skipWaiting()})())});
self.addEventListener("activate",e=>{e.waitUntil((async()=>{const keys=await caches.keys();await Promise.all(keys.filter(k=>k.startsWith(CACHE_PREFIX)&&k!==CACHE_VERSION).map(k=>caches.delete(k)));if(self.registration.navigationPreload){try{if(DESKTOP_SAFARI)await self.registration.navigationPreload.enable();else await self.registration.navigationPreload.disable()}catch(_e){}}await self.clients.claim()})())});
self.addEventListener("message",e=>{if(e.data&&e.data.type==="SKIP_WAITING")self.skipWaiting()});
async function offlineFallback(request){return(await caches.match(request,{ignoreSearch:false}))||(await caches.match(request,{ignoreSearch:true}))||(await caches.match(INDEX_URL))||new Response("Sin conexión",{status:503,headers:{"Content-Type":"text/plain; charset=utf-8"}})}
async function shellFast(e){const c=await caches.open(CACHE_VERSION);const cached=await c.match(INDEX_URL);if(cached)return cached;try{const r=await fetch(e.request);if(r&&r.ok)await c.put(INDEX_URL,r.clone());return r}catch(_e){return offlineFallback(e.request)}}
async function networkFirst(e){try{const preload=await e.preloadResponse;if(preload){if(preload.ok){const c=await caches.open(CACHE_VERSION);await c.put(e.request,preload.clone())}return preload}const r=await fetch(e.request);if(r&&r.ok){const c=await caches.open(CACHE_VERSION);await c.put(e.request,r.clone())}return r}catch(_e){return offlineFallback(e.request)}}
function stale(e){const cachePromise=caches.open(CACHE_VERSION);const cachedPromise=cachePromise.then(c=>c.match(e.request,{ignoreSearch:false}));const networkPromise=fetch(e.request).then(async r=>{if(r&&r.ok){const c=await cachePromise;await c.put(e.request,r.clone())}return r}).catch(()=>null);e.waitUntil(networkPromise.then(()=>undefined).catch(()=>undefined));return cachedPromise.then(async cached=>{if(cached)return cached;const r=await networkPromise;if(r)return r;return offlineFallback(e.request)})}
async function cachedPatch(path){const url=absolute(path);const c=await caches.open(CACHE_VERSION);let r=await c.match(url);if(r)return r;try{r=await fetch(releaseRequest(url));if(r&&r.ok)await c.put(url,r.clone());return r}catch(_e){return null}}
async function eternaCoreWithHotfix(e){const basePromise=cachedPatch(ETERNA_CORE_PATH);const patchPromise=cachedPatch(ETERNA_HOTFIX_PATH);const compactPromise=cachedPatch(ETERNA_DESKTOP_COMPACT_PATH);const[base,patch,compact]=await Promise.all([basePromise,patchPromise,compactPromise]);if(!base||!patch||!patch.ok)return base||offlineFallback(e.request);const[coreText,patchText,compactText]=await Promise.all([base.text(),patch.text(),compact&&compact.ok?compact.text():Promise.resolve("")]);const headers=new Headers(base.headers);headers.set("Content-Type","application/javascript; charset=utf-8");headers.set("Cache-Control","no-cache");["Content-Length","Content-Encoding","ETag","Last-Modified"].forEach(h=>headers.delete(h));return new Response(coreText+"\n\n/* --- ETERNA HF injected by SW --- */\n"+patchText+"\n\n/* --- ETERNA desktop compact injected by SW --- */\n"+compactText+"\n",{status:base.status,statusText:base.statusText,headers})}
async function eternaExperienceWithMicOnly(e){const basePromise=cachedPatch(ETERNA_EXPERIENCE_PATH);const micPromise=cachedPatch(ETERNA_MIC_ONLY_PATH);const[base,mic]=await Promise.all([basePromise,micPromise]);if(!base)return offlineFallback(e.request);const[baseText,micText]=await Promise.all([base.text(),mic&&mic.ok?mic.text():Promise.resolve("")]);const headers=new Headers(base.headers);headers.set("Content-Type","application/javascript; charset=utf-8");headers.set("Cache-Control","no-cache");["Content-Length","Content-Encoding","ETag","Last-Modified"].forEach(h=>headers.delete(h));return new Response("/* --- ETERNA MIC ONLY V4 PRE-CAPTURE --- */\n"+micText+"\n\n"+baseText,{status:base.status,statusText:base.statusText,headers})}
async function cocoBootstrapWithProductUx(e){const basePromise=stale(e);const patchPromise=cachedPatch(PRODUCT_UX_PATH);const retoPromise=cachedPatch(RETO_2026_PATH);const[base,patch,reto]=await Promise.all([basePromise,patchPromise,retoPromise]);if(!base||!patch||!patch.ok)return base||offlineFallback(e.request);const[baseText,patchText,retoText]=await Promise.all([base.text(),patch.text(),reto&&reto.ok?reto.text():Promise.resolve("")]);const headers=new Headers(base.headers);headers.set("Content-Type","application/javascript; charset=utf-8");headers.set("Cache-Control","no-cache");["Content-Length","Content-Encoding","ETag","Last-Modified"].forEach(h=>headers.delete(h));return new Response(baseText+"\n\n/* --- COCO PRODUCT UX injected by SW --- */\n"+patchText+"\n\n/* --- RETO COCO 2026 disabled cleanup --- */\n"+retoText+"\n",{status:base.status,statusText:base.statusText,headers})}
self.addEventListener("fetch",e=>{if(e.request.method!=="GET")return;const u=new URL(e.request.url);if(u.origin!==self.location.origin)return;const doc=e.request.mode==="navigate"||e.request.destination==="document";const shellDoc=doc&&(u.pathname===SCOPE_URL.pathname||u.pathname===new URL("index.html",SCOPE_URL).pathname);const eternaCore=u.pathname===new URL(ETERNA_CORE_PATH,SCOPE_URL).pathname;const eternaExperience=u.pathname===new URL(ETERNA_EXPERIENCE_PATH,SCOPE_URL).pathname;const cocoBootstrap=u.pathname===new URL(COCO_BOOTSTRAP_PATH,SCOPE_URL).pathname;const identity=u.pathname===new URL("./coco-v155-identity.js",SCOPE_URL).pathname;if(shellDoc){e.respondWith(DESKTOP_SAFARI?networkFirst(e):shellFast(e));return}if(doc){e.respondWith(networkFirst(e));return}if(u.pathname===new URL(ETERNA_VOICE_AUTOCUT_PATH,SCOPE_URL).pathname){e.respondWith(cachedPatch(ETERNA_VOICE_AUTOCUT_PATH).then(r=>r||offlineFallback(e.request)));return}if(eternaCore){e.respondWith(eternaCoreWithHotfix(e));return}if(eternaExperience){e.respondWith(eternaExperienceWithMicOnly(e));return}if(cocoBootstrap){e.respondWith(cocoBootstrapWithProductUx(e));return}if(identity){e.respondWith(stale(e));return}e.respondWith(stale(e))});
