// Public curricular evidence only. Exact payload hashes; fixed tables, project and snapshot.
// No child records, arbitrary SQL, credential export or production deployment.
import{readFileSync,writeFileSync,mkdirSync}from'node:fs';import{createHash,randomBytes}from'node:crypto';import{execFileSync}from'node:child_process';import assert from'node:assert/strict';
const snapshot='eterna-curriculum-map-2026.09.12-v1',release='eterna-library-2026.09-v6-310-traceable-12c672',script='coco-eterna-v159',dir='traceable-map-import-evidence';mkdirSync(dir,{recursive:true});
const hash=x=>createHash('sha256').update(x).digest('hex'),json=p=>JSON.parse(readFileSync(p)),base='curriculum-traceability-evidence';
const proof=json('traceable-private-evidence/report.json');assert.equal(proof.phase,'canonical-private-verified');assert.equal(proof.synthetic_cleanup.deleted,true);assert.equal(proof.draft_content.lessons,310);
const inventory=json(base+'/national/national-inventory.json'),versions=json(base+'/mapping/regulatory-version-chain.json'),retrieval=json('.official-refreshed/retrieval.json');assert.equal(inventory.rows,9033);
const sources=inventory.sources.map(s=>{const meta=versions.national_authority_metadata.find(v=>v.source_key===s.source_key);assert.ok(meta);return{snapshot_id:snapshot,source_key:s.source_key,official_url:'https://www.boe.es/buscar/act.php?id='+s.source_key,title:meta.title,jurisdiction:'ES-STATE',source_kind:'national_annex',original_sha256:s.source_sha256,evidence:{inventory:s,version:meta,original_archive_run:34678919953,full_regional_consolidation:false}}});
for(const key of ['madrid-bachillerato-original','madrid-modificacion-59-2024','madrid-optativas-114-2025']){const r=retrieval.regional.find(r=>r.key===key);assert.equal(r.text_extracted,true);sources.push({snapshot_id:snapshot,source_key:key,official_url:r.official_url,title:({'madrid-bachillerato-original':'Madrid: Decreto 64/2022, original auténtico','madrid-modificacion-59-2024':'Madrid: Decreto 59/2024, modificación','madrid-optativas-114-2025':'Madrid: Orden 114/2025, catálogo de optativas'})[key],jurisdiction:'ES-MD',source_kind:key==='madrid-bachillerato-original'?'regional_original':'regional_amendment',original_sha256:r.sha256,evidence:{...r,selected_findings:versions.selected_amendment_findings.filter(f=>f.source_file===key+'.pdf'),raw_archive_run:34678919953,all_annexes_semantically_mapped:false}})}
const units=readFileSync(base+'/national/units.jsonl','utf8').trim().split('\n').map(JSON.parse).map(u=>{assert.equal(hash(u.text),u.text_sha256);return{snapshot_id:snapshot,unit_id:u.unit_id,source_key:u.source_key,stage:u.stage,jurisdiction:u.jurisdiction,subject:u.subject,offering:u.offering,course_band:u.course_band,kind:u.kind,official_code:u.official_code,body:u.text,text_sha256:u.text_sha256,source_ordinal:u.source_ordinal,official_url:u.official_url,evidence:{source_sha256:u.source_sha256,competence_code:u.competence_code,knowledge_block:u.knowledge_block,knowledge_subblock:u.knowledge_subblock,metadata:u.metadata}}});
const links=[];
for(const[file,status,unitfield]of [['lesson-subject-map.json','subject_reference','source_subject_unit_id'],['element-link-candidates.json','candidate_not_validated','unit_id'],['reviewed-partial-links.json','ai_reviewed_partial_support','unit_id']])for(const row of json(base+'/mapping/'+file)){assert.equal(row.library_release_id,release);if(row.status)assert.equal(row.status,status);links.push({snapshot_id:snapshot,library_lesson_id:release+':'+row.lesson_id,unit_id:row[unitfield],review_status:status,whole_criterion_mastery_claimed:false,human_teacher_reviewed:false,evidence:row})}
assert.equal(sources.length,7);assert.equal(units.length,9033);assert.equal(links.length,1359);
const tables={eterna_curriculum_map_sources:sources,eterna_curriculum_elements:units,eterna_curriculum_lesson_links:links};const bodies=[];
for(const[table,rows]of Object.entries(tables)){let batch=[],bytes=0;for(const row of rows){const size=Buffer.byteLength(JSON.stringify(row));if(batch.length&&(batch.length>=60||bytes+size>400000)){bodies.push(JSON.stringify({table,rows:batch}));batch=[];bytes=0}batch.push(row);bytes+=size}if(batch.length)bodies.push(JSON.stringify({table,rows:batch}))}
const verifyBody=JSON.stringify({verify:true}),allowedHashes=[...bodies,verifyBody].map(hash),access=randomBytes(32).toString('hex');console.log('::add-mask::'+access);
const token=String(process.env.CLOUDFLARE_API_TOKEN||'').replace(/\s/g,''),account=String(process.env.CLOUDFLARE_ACCOUNT_INPUT||'').replace(/^https:\/\/dash.cloudflare.com\//,'').split('/')[0];assert.ok(token&&/^[a-f0-9]{32}$/i.test(account));console.log('::add-mask::'+token);console.log('::add-mask::'+account);
async function cf(path){const r=await fetch(`https://api.cloudflare.com/client/v4/accounts/${account}/workers/scripts/${script}${path}`,{headers:{Authorization:'Bearer '+token},signal:AbortSignal.timeout(30000)});const p=await r.json();assert.ok(r.ok&&p.success!==false,'Cloudflare read failed '+r.status);return p.result}
async function live(){const p=await cf('/deployments'),d=(Array.isArray(p)?p:p.deployments)?.[0];assert.ok(d?.versions?.length===1&&d.versions[0].percentage===100);return d}
const baseline=await live();assert.equal(baseline.versions[0].version_id,'ce846fe8-2f9a-4c4e-ba72-397dcc14e2db','Concurrent production change; stop');const original=await cf('/versions/'+baseline.versions[0].version_id),bindings=original.resources.bindings;
for(const b of bindings)assert.ok(['plain_text','secret_text','ai'].includes(b.type),'Unmapped binding; refuse to alter configuration');
const vars=Object.fromEntries(bindings.filter(b=>b.type==='plain_text').map(b=>[b.name,b.text])),rt=original.resources.script_runtime||{};
const generated=`const SNAPSHOT=${JSON.stringify(snapshot)},ALLOWED=new Set(${JSON.stringify(allowedHashes)}),TABLES=new Set(${JSON.stringify(Object.keys(tables))}),EXPIRES=${Date.now()+20*60000};
async function sha(v){return [...new Uint8Array(await crypto.subtle.digest('SHA-256',new TextEncoder().encode(v)))].map(x=>x.toString(16).padStart(2,'0')).join('')}
export default{async fetch(request,env){
 const reply=(p,status=200)=>new Response(JSON.stringify(p),{status,headers:{'Content-Type':'application/json','Cache-Control':'no-store','X-Robots-Tag':'noindex'}});
 if(Date.now()>EXPIRES||request.method!=='POST'||new URL(request.url).pathname!=='/__fixed_curriculum_map')return reply({error:'NOT_FOUND'},404);
 if(await sha((request.headers.get('Authorization')||'').replace(/^Bearer /,''))!==${JSON.stringify(hash(access))})return reply({error:'UNAUTHORIZED'},401);
 let base;try{const u=new URL(env.SUPABASE_URL);if(u.protocol!=='https:'||u.hostname!=='fcatttsfufjiphgohgwp.supabase.co')throw Error();base=u.origin+'/rest/v1/'}catch{return reply({error:'PROJECT_REJECTED'},403)}
 const raw=await request.text();if(raw.length>600000||!ALLOWED.has(await sha(raw)))return reply({error:'PAYLOAD_REJECTED'},403);
 const key=env.SUPABASE_SECRET_KEY||env.SUPABASE_SERVICE_ROLE_KEY;if(!key)return reply({error:'CONFIGURATION'},500);
 const headers={apikey:key,'Content-Type':'application/json',Prefer:'resolution=merge-duplicates,return=minimal'};if(!key.startsWith('sb_secret_'))headers.Authorization='Bearer '+key;
 const gate=await fetch(base+'eterna_curriculum_map_snapshots?snapshot_id=eq.'+SNAPSHOT+'&select=status,library_release_id',{headers});const state=await gate.json();if(!gate.ok||state.length!==1||state[0].status!=='draft'||state[0].library_release_id!==${JSON.stringify(release)})return reply({error:'SNAPSHOT_NOT_DRAFT'},409);
 const payload=JSON.parse(raw);
 if(payload.verify){const counts={};for(const table of TABLES){const r=await fetch(base+table+'?snapshot_id=eq.'+SNAPSHOT+'&select=snapshot_id',{headers:{...headers,Prefer:'count=exact',Range:'0-0'}});if(!r.ok)return reply({error:'VERIFY_FAILED'},500);counts[table]=Number((r.headers.get('Content-Range')||'').split('/')[1])}return reply({ok:true,counts})}
 if(!TABLES.has(payload.table)||!Array.isArray(payload.rows)||payload.rows.some(r=>r.snapshot_id!==SNAPSHOT))return reply({error:'SCOPE_REJECTED'},403);
 const r=await fetch(base+payload.table,{method:'POST',headers,body:JSON.stringify(payload.rows)});if(!r.ok){const e=await r.json().catch(()=>({}));return reply({error:'WRITE_FAILED',http_status:r.status,code:e.code||null},502)}
 return reply({ok:true,table:payload.table,rows:payload.rows.length})
}};`;
writeFileSync('eterna-worker/src/.fixed-map-import.js',generated);execFileSync(process.execPath,['--check','eterna-worker/src/.fixed-map-import.js']);
const config={name:script,main:'src/.fixed-map-import.js',compatibility_date:rt.compatibility_date,compatibility_flags:rt.compatibility_flags||[],vars};const ai=bindings.find(b=>b.type==='ai');if(ai)config.ai={binding:ai.name};if(rt.limits?.cpu_ms)config.limits={cpu_ms:rt.limits.cpu_ms};if(rt.usage_model)config.usage_model=rt.usage_model;writeFileSync('eterna-worker/.fixed-map-import.json',JSON.stringify(config));
let output;try{output=execFileSync('npx',['wrangler','versions','upload','--config','.fixed-map-import.json','--keep-vars','--message','Expiring exact public curriculum map import; NEVER deploy'],{cwd:'eterna-worker',encoding:'utf8',timeout:180000,maxBuffer:8*1024*1024,env:{...process.env,CLOUDFLARE_API_TOKEN:token,CLOUDFLARE_ACCOUNT_ID:account,CI:'true'}})}catch(e){throw Error('Private upload failed '+e.status+'; confidential output withheld')}
const url=output.match(/Version Preview URL:\s*(https:\/\/[^\s]+)/)?.[1];assert.ok(url&&/^https:\/\/[a-f0-9-]+-coco-eterna-v159\.chatinmobiliario\.workers\.dev$/.test(url));assert.equal((await live()).id,baseline.id);
assert.equal((await fetch(url+'/__fixed_curriculum_map',{method:'POST'})).status,401);
const report={snapshot_id:snapshot,release_id:release,phase:'importing',production_changed:false,child_data_accessed:false,completed_batches:0,expected_counts:Object.fromEntries(Object.entries(tables).map(([k,v])=>[k,v.length]))};const save=()=>writeFileSync(dir+'/report.json',JSON.stringify(report,null,2));save();
async function post(body){let last;for(let i=0;i<3;i++){try{const r=await fetch(url+'/__fixed_curriculum_map',{method:'POST',headers:{Authorization:'Bearer '+access,'Content-Type':'application/json'},body,signal:AbortSignal.timeout(60000)});const p=await r.json();assert.ok(r.ok&&p.ok,JSON.stringify(p));return p}catch(e){last=e;await new Promise(r=>setTimeout(r,1000))}}throw last}
try{for(const body of bodies){await post(body);report.completed_batches++;save()}report.actual_counts=(await post(verifyBody)).counts;assert.deepEqual(report.actual_counts,report.expected_counts);assert.equal((await live()).id,baseline.id);report.phase='draft-map-import-verified';report.verified_at=new Date().toISOString();save();console.log(JSON.stringify(report))}catch(e){report.phase='draft-map-import-incomplete';report.error=String(e.message).slice(0,300);save();throw e}
