// Promote only the exact canonical Worker already tested with actual auth and Supabase.
// No uploads, no synthetic wrapper deployment, no arbitrary changes to bindings.
import{readFileSync,writeFileSync,mkdirSync}from'node:fs';import{createHash}from'node:crypto';import{execFileSync}from'node:child_process';import assert from'node:assert/strict';
const script='coco-eterna-v159',production='https://coco-eterna-v159.chatinmobiliario.workers.dev';
const release='eterna-library-2026.09-v6-310-traceable-12c672',oldRelease='eterna-library-2026.09-v5-304-panel-ffe822';
const expectedMain='86ddb64a64554f83408dfb2afeccf45dd486c455',expectedBase='ce846fe8-2f9a-4c4e-ba72-397dcc14e2db',expectedCandidate='9480a578-cca5-4412-bbfd-fbfbf27c11c1';
const proof=JSON.parse(readFileSync('.private-proof/report.json')),build=JSON.parse(readFileSync('.build-proof/report.json'));
assert.equal(proof.phase,'canonical-private-verified');assert.equal(proof.release,release);assert.equal(proof.base_version,expectedBase);assert.equal(proof.candidate_version,expectedCandidate);
assert.equal(proof.requests.length,140);assert.equal(proof.synthetic_cleanup.ok,true);assert.equal(proof.synthetic_cleanup.deleted,true);assert.equal(proof.synthetic_cleanup.identities,2);
assert.equal(proof.curated_teaching_turns,40);assert.equal(proof.generated_teaching_turns,44);assert.equal(proof.protocol_turns,56);assert.equal(proof.procedural_families_tested.length,22);
assert.equal(proof.draft_content.lessons,310);assert.equal(proof.draft_content.protocols,56);assert.equal(proof.draft_content.hash_mismatches,0);assert.equal(build.tests_failed,0);assert.equal(build.tests_passed,753);assert.equal(proof.regressions_passed,753);
assert.equal(build.generated_question_instances_independently_checked,19800);assert.equal(proof.production_quota_unchanged,true);assert.equal(proof.real_pupil_data_used,false);
for(const q of proof.requests){assert.equal(q.generation_model_calls,0);assert.equal(q.generation_tokens,0)}
for(const field of ['lower_grade_filtered','invalid_terms_rejected','anonymous_denied'])assert.equal(proof.compass_probe[field],true,field);
const hash=v=>createHash('sha256').update(v).digest('hex');
for(const[path,p]of Object.entries(proof.source_hashes))assert.equal(hash(readFileSync(path)),p.sha256,'Not the tested source '+path);
assert.equal(hash(readFileSync('eterna-worker/src/index.js')),'bc425e8f9e0e3eb5fa8e7fe6fbbd5520b72bdcae6cf6c1f0397578851da79964');
const source=readFileSync('eterna-worker/src/index.js','utf8');assert.ok(!source.includes('__synthetic_library_qa'));assert.ok(!source.includes('__fixed_curriculum_map'));
assert.equal(execFileSync('git',['rev-parse','HEAD:eterna-worker/src/index.js'],{encoding:'utf8'}).trim(),proof.source_hashes['eterna-worker/src/index.js'].sha);
const token=String(process.env.CLOUDFLARE_API_TOKEN||'').replace(/\s/g,''),account=String(process.env.CLOUDFLARE_ACCOUNT_INPUT||'').replace(/^https:\/\/dash.cloudflare.com\//,'').split('/')[0];assert.ok(token&&/^[a-f0-9]{32}$/i.test(account));console.log('::add-mask::'+token);console.log('::add-mask::'+account);
async function mainHead(){const r=await fetch('https://api.github.com/repos/diegopenn-png/coco-en-forma/git/ref/heads/main',{headers:{Authorization:'Bearer '+process.env.GH_TOKEN,Accept:'application/vnd.github+json'},signal:AbortSignal.timeout(25000)});assert.equal(r.status,200);return(await r.json()).object.sha}
async function cf(path){const r=await fetch(`https://api.cloudflare.com/client/v4/accounts/${account}/workers/scripts/${script}${path}`,{headers:{Authorization:'Bearer '+token},signal:AbortSignal.timeout(30000)});const p=await r.json();assert.ok(r.ok&&p.success!==false,'Cloudflare read failed '+r.status);return p.result}
async function live(){const p=await cf('/deployments'),d=(Array.isArray(p)?p:p.deployments)?.[0];assert.ok(d?.versions?.length===1&&d.versions[0].percentage===100,'Expected one production version');return d}
const canon=v=>Array.isArray(v)?v.map(canon):v&&typeof v==='object'?Object.fromEntries(Object.keys(v).sort().map(k=>[k,canon(v[k])])):v;
const fingerprint=v=>hash(JSON.stringify(canon(v))),allowed=new Set(['ETERNA_LIBRARY_RELEASE','ETERNA_EXERCISE_FACTORY','ETERNA_CURRICULAR_COMPASS']);
const reduced=v=>v.resources.bindings.filter(b=>!allowed.has(b.name)).sort((a,b)=>a.name.localeCompare(b.name));
const baseline=await live();assert.equal(baseline.versions[0].version_id,expectedBase,'Concurrent production change; stop');assert.equal(baseline.id,proof.base_deployment);assert.equal(await mainHead(),expectedMain);
const old=await cf('/versions/'+expectedBase),candidate=await cf('/versions/'+expectedCandidate);
assert.equal(old.resources.script.etag,proof.base_code_etag);assert.equal(candidate.resources.script.etag,proof.candidate_code_etag);
assert.equal(fingerprint(reduced(candidate)),fingerprint(reduced(old)),'Unrelated binding changed');assert.equal(fingerprint(candidate.resources.script_runtime),fingerprint(old.resources.script_runtime),'Runtime changed');
const vars=Object.fromEntries(candidate.resources.bindings.filter(b=>b.type==='plain_text').map(b=>[b.name,b.text]));
assert.equal(vars.ENABLE_ETERNA_LIBRARY,'true');assert.equal(vars.ETERNA_LIBRARY_RELEASE,release);assert.equal(vars.ETERNA_EXERCISE_FACTORY,'v1');assert.equal(vars.ETERNA_CURRICULAR_COMPASS,'v1');
async function health(url,newVersion){const r=await fetch(url+'/health',{headers:{'Cache-Control':'no-cache'},signal:AbortSignal.timeout(20000)});assert.equal(r.status,200);const p=await r.json();assert.equal(p.ok,true);assert.equal(p.owned_library?.enabled,true);assert.equal(p.owned_library.release,newVersion?release:oldRelease);assert.equal(p.owned_library.lessons,newVersion?310:304);assert.equal(p.owned_library.protocols,56);assert.equal(p.owned_library.curriculum_complete,false);if(newVersion){assert.equal(p.exercise_factory?.enabled,true);assert.equal(p.exercise_factory.families,22);assert.equal(p.curricular_compass?.enabled,true);assert.equal(p.curricular_compass.source_elements,9033)}return p}
const configuration=p=>fingerprint({provider:p.ai_provider,models:p.model_configuration,features:p.features,supabase:p.supabase_configured,stripe:p.stripe_configured,openai:p.openai_configured,cloudflare:p.cloudflare_ai_configured});
async function denied(url){for(const path of ['/v1/chat','/v1/chat-job','/v1/transcribe']){const r=await fetch(url+path,{method:'POST',headers:{Origin:'https://cocoenforma.com'},signal:AbortSignal.timeout(20000)});assert.equal(r.status,401,'Access gate no longer blocks '+path)}}
const oldHealth=await health(production,false),candidateHealth=await health(proof.candidate_url,true);assert.equal(configuration(oldHealth),configuration(candidateHealth));await denied(production);await denied(proof.candidate_url);
for(const b of candidate.resources.bindings)assert.ok(['plain_text','secret_text','ai'].includes(b.type),'Unmapped binding type');
const rt=candidate.resources.script_runtime||{},ai=candidate.resources.bindings.find(b=>b.type==='ai'),config={name:script,main:'src/index.js',compatibility_date:rt.compatibility_date,compatibility_flags:rt.compatibility_flags||[],vars};if(ai)config.ai={binding:ai.name};if(rt.limits?.cpu_ms)config.limits={cpu_ms:rt.limits.cpu_ms};if(rt.usage_model)config.usage_model=rt.usage_model;
writeFileSync('eterna-worker/.sprint-production.json',JSON.stringify(config));mkdirSync('sprint-production-evidence',{recursive:true});
const report={phase:'pre-promotion',production_commit:expectedMain,release,base_version:expectedBase,candidate_version:expectedCandidate,source_sha256:proof.source_sha256,content_sha256:proof.source_hashes['eterna-worker/src/library/content-v1.js'].sha256,canonical_etag:proof.candidate_code_etag,lessons:310,curated_questions:930,protocols:56,procedural_families:22,national_source_elements:9033,tests_passed:753,tests_failed:0,independently_checked_generated_instances:19800,private_requests:140,private_generated_turns:44,private_latency:proof.latency,private_zero_generation_tokens:true,synthetic_identities_deleted:2,microphone_unchanged:true,frontend_unchanged:true,models_unchanged:true,quota_unchanged:true,unrelated_bindings_unchanged:true,runtime_unchanged:true,production_changed:false,full_curriculum_complete:false,human_teacher_reviewed:false};
const save=()=>writeFileSync('sprint-production-evidence/report.json',JSON.stringify(report,null,2));save();
function deploy(id,message){try{execFileSync('npx',['wrangler','versions','deploy',id+'@100%','--name',script,'--config','.sprint-production.json','--message',message,'--yes'],{cwd:'eterna-worker',env:{...process.env,CLOUDFLARE_API_TOKEN:token,CLOUDFLARE_ACCOUNT_ID:account,CI:'true'},encoding:'utf8',timeout:180000,maxBuffer:8*1024*1024})}catch(e){throw Error('Controlled promotion failed '+e.status+'; confidential output omitted')}}
assert.equal((await live()).id,baseline.id);assert.equal(await mainHead(),expectedMain);let attempted=false;
try{
 attempted=true;deploy(expectedCandidate,'Enable exact tested exercise factory and bounded curricular compass; preserve voice, model and quotas');let current,passed=false;
 for(let i=0;i<6;i++){current=await live();if(current.versions[0].version_id===expectedCandidate){try{const liveHealth=await health(production,true);assert.equal(configuration(liveHealth),configuration(oldHealth));await denied(production);report.live_features={owned_library:liveHealth.owned_library,exercise_factory:liveHealth.exercise_factory,curricular_compass:liveHealth.curricular_compass};passed=true;break}catch{}}await new Promise(r=>setTimeout(r,5000))}
 assert.ok(passed,'Production verification failed');assert.equal(await mainHead(),expectedMain);report.phase='production-verified';report.production_changed=true;report.production_version=expectedCandidate;report.deployment_id=current.id;report.verified_at=new Date().toISOString();save();console.log(JSON.stringify(report));
}catch(e){report.phase='not-ready';report.error=String(e.message).slice(0,300);if(attempted){const current=await live();if(current.versions[0].version_id===expectedCandidate){deploy(expectedBase,'Rollback failed deterministic-practice promotion');report.rollback_verified=(await live()).versions[0].version_id===expectedBase}else report.rollback_skipped_concurrent_change=true}save();throw e}
