// Exact-version promotion for the already privately verified adjacent-round fix.
// No code uploads, library imports, quota/flag changes, or synthetic helper deployment.
import{readFileSync,writeFileSync,mkdirSync}from'node:fs';import{createHash}from'node:crypto';import{execFileSync}from'node:child_process';import assert from'node:assert/strict';
const expectedMain=process.env.PUBLISH_COMMIT,script='coco-eterna-v159',production='https://coco-eterna-v159.chatinmobiliario.workers.dev',release='eterna-library-2026.09-v6-310-traceable-12c672',expectedBase='9480a578-cca5-4412-bbfd-fbfbf27c11c1';
assert.match(expectedMain,/^[a-f0-9]{40}$/);
const proof=JSON.parse(readFileSync('.proof/next-round-private/report.json')),build=JSON.parse(readFileSync('.proof/next-round-build/report.json'));
assert.equal(proof.phase,'canonical-private-verified');assert.equal(proof.base_version,expectedBase);assert.equal(proof.requests.length,52);assert.equal(proof.adjacent_round_checks.length,8);assert.equal(proof.synthetic_cleanup.ok,true);assert.equal(proof.synthetic_cleanup.deleted,true);assert.equal(proof.real_pupil_data_used,false);assert.equal(proof.bindings_unchanged,true);assert.equal(proof.runtime_unchanged,true);assert.equal(proof.regressions_passed,779);assert.equal(build.tests_passed,779);assert.equal(build.tests_failed,0);
for(const q of proof.requests){assert.equal(q.generation_model_calls,0);assert.equal(q.generation_tokens,0)}
const hash=v=>createHash('sha256').update(v).digest('hex');
for(const[path,p]of Object.entries(proof.source_hashes))assert.equal(hash(readFileSync(path)),p.sha256,path);
assert.equal(hash(readFileSync('eterna-worker/src/library/procedural-v1.js')),'371f32609b1b2c3d4ba50ab4f67a487629f6cc536ced031a583e4d0ca6e46d98');
const candidateId=proof.candidate_version;assert.match(candidateId,/^[a-f0-9-]{36}$/);assert.notEqual(candidateId,expectedBase);
const token=String(process.env.CLOUDFLARE_API_TOKEN||'').replace(/\s/g,''),account=String(process.env.CLOUDFLARE_ACCOUNT_INPUT||'').replace(/^https:\/\/dash.cloudflare.com\//,'').split('/')[0];assert.ok(token&&/^[a-f0-9]{32}$/i.test(account));console.log('::add-mask::'+token);console.log('::add-mask::'+account);
async function mainHead(){const r=await fetch('https://api.github.com/repos/diegopenn-png/coco-en-forma/git/ref/heads/main',{headers:{Authorization:'Bearer '+process.env.GH_TOKEN,Accept:'application/vnd.github+json'},signal:AbortSignal.timeout(20000)});assert.equal(r.status,200);return(await r.json()).object.sha}
async function cf(path){const r=await fetch(`https://api.cloudflare.com/client/v4/accounts/${account}/workers/scripts/${script}${path}`,{headers:{Authorization:'Bearer '+token},signal:AbortSignal.timeout(25000)});const p=await r.json();assert.ok(r.ok&&p.success!==false,'Cloudflare read failed');return p.result}
async function live(){const p=await cf('/deployments'),d=(Array.isArray(p)?p:p.deployments)?.[0];assert.ok(d?.versions?.length===1&&d.versions[0].percentage===100);return d}
const canon=v=>Array.isArray(v)?v.map(canon):v&&typeof v==='object'?Object.fromEntries(Object.keys(v).sort().map(k=>[k,canon(v[k])])):v,fp=v=>hash(JSON.stringify(canon(v)));
const baseline=await live();assert.equal(baseline.versions[0].version_id,expectedBase);assert.equal(baseline.id,proof.base_deployment);assert.equal(await mainHead(),expectedMain);
const old=await cf('/versions/'+expectedBase),candidate=await cf('/versions/'+candidateId);
assert.equal(old.resources.script.etag,proof.base_code_etag);assert.equal(candidate.resources.script.etag,proof.candidate_code_etag);
const sorted=v=>[...v.resources.bindings].sort((a,b)=>a.name.localeCompare(b.name));assert.equal(fp(sorted(candidate)),fp(sorted(old)),'Any configuration/binding change is forbidden');assert.equal(fp(candidate.resources.script_runtime),fp(old.resources.script_runtime));
async function health(url){const r=await fetch(url+'/health',{headers:{'Cache-Control':'no-cache'},signal:AbortSignal.timeout(20000)});assert.equal(r.status,200);const p=await r.json();assert.equal(p.ok,true);assert.equal(p.owned_library?.enabled,true);assert.equal(p.owned_library.release,release);assert.equal(p.owned_library.lessons,310);assert.equal(p.owned_library.protocols,56);assert.equal(p.exercise_factory?.enabled,true);assert.equal(p.exercise_factory.families,22);assert.equal(p.curricular_compass?.enabled,true);return p}
const configFingerprint=p=>fp({provider:p.ai_provider,models:p.model_configuration,features:p.features,supabase:p.supabase_configured,stripe:p.stripe_configured,openai:p.openai_configured,cloudflare:p.cloudflare_ai_configured});
async function denied(url){for(const path of ['/v1/chat','/v1/chat-job','/v1/transcribe']){const r=await fetch(url+path,{method:'POST',headers:{Origin:'https://cocoenforma.com'},signal:AbortSignal.timeout(20000)});assert.equal(r.status,401,path)}}
const oldHealth=await health(production);assert.equal(configFingerprint(await health(proof.candidate_url)),configFingerprint(oldHealth));await denied(proof.candidate_url);
for(const b of candidate.resources.bindings)assert.ok(['plain_text','secret_text','ai'].includes(b.type));
const vars=Object.fromEntries(candidate.resources.bindings.filter(b=>b.type==='plain_text').map(b=>[b.name,b.text])),rt=candidate.resources.script_runtime||{},ai=candidate.resources.bindings.find(b=>b.type==='ai');
const config={name:script,main:'src/index.js',compatibility_date:rt.compatibility_date,compatibility_flags:rt.compatibility_flags||[],vars};if(ai)config.ai={binding:ai.name};if(rt.limits?.cpu_ms)config.limits={cpu_ms:rt.limits.cpu_ms};if(rt.usage_model)config.usage_model=rt.usage_model;
writeFileSync('eterna-worker/.next-round-publish.json',JSON.stringify(config));mkdirSync('next-round-production',{recursive:true});
const report={phase:'pre-promotion',production_commit:expectedMain,release,base_version:expectedBase,candidate_version:candidateId,procedural_sha256:proof.source_hashes['eterna-worker/src/library/procedural-v1.js'].sha256,candidate_etag:proof.candidate_code_etag,tests_passed:779,private_requests:52,private_adjacent_round_checks:8,local_adjacent_transitions_checked:26400,synthetic_cleanup_verified:true,generation_tokens_on_tested_routes:0,existing_seeded_question_generation_unchanged:true,microphone_changed:false,frontend_changed:false,bindings_changed:false,quota_changed:false,model_changed:false,content_imported:false,repeat_exclusion_scope:'immediately_previous_round_only',production_changed:false};
const save=()=>writeFileSync('next-round-production/report.json',JSON.stringify(report,null,2));save();
function deploy(id,message){try{execFileSync('npx',['wrangler','versions','deploy',id+'@100%','--name',script,'--config','.next-round-publish.json','--message',message,'--yes'],{cwd:'eterna-worker',env:{...process.env,CLOUDFLARE_API_TOKEN:token,CLOUDFLARE_ACCOUNT_ID:account,CI:'true'},encoding:'utf8',timeout:120000,maxBuffer:8*1024*1024})}catch(e){throw Error('Controlled promotion failed; confidential output omitted')}}
assert.equal((await live()).id,baseline.id);assert.equal(await mainHead(),expectedMain);let attempted=false;
try{
 attempted=true;deploy(candidateId,'Fix other-round question repetition only; preserve current questions and all configuration');let current,passed=false;
 for(let i=0;i<6;i++){current=await live();if(current.versions[0].version_id===candidateId){try{const h=await health(production);assert.equal(configFingerprint(h),configFingerprint(oldHealth));await denied(production);passed=true;break}catch{}}await new Promise(r=>setTimeout(r,4000))}
 assert.ok(passed,'Postpublication verification failed');assert.equal(await mainHead(),expectedMain);report.phase='production-verified';report.production_changed=true;report.production_version=candidateId;report.deployment_id=current.id;report.verified_at=new Date().toISOString();save();console.log(JSON.stringify(report));
}catch(e){report.phase='not-ready';report.error=String(e.message).slice(0,250);if(attempted){const current=await live();if(current.versions[0].version_id===candidateId){deploy(expectedBase,'Rollback failed next-round-only fix');report.rollback_verified=(await live()).versions[0].version_id===expectedBase}else report.rollback_skipped_concurrent_change=true}save();throw e}
