import{readFileSync,writeFileSync}from'node:fs';import assert from'node:assert/strict';
const build=JSON.parse(readFileSync('content-410-evidence/report.json')),rs=[1,2].map(i=>JSON.parse(readFileSync(`content-410-private/group-${i}/report.json`)));
for(const[i,r]of rs.entries()){
 assert.equal(r.phase,'canonical-private-verified');assert.equal(r.synthetic_group,i+1);assert.equal(r.release,build.release_id);assert.equal(r.regressions_passed,build.tests_passed);assert.equal(r.requests.length,42);assert.equal(r.new_lessons_checked.length,20);
 assert.equal(r.synthetic_cleanup.ok,true);assert.equal(r.synthetic_cleanup.deleted,true);assert.equal(r.production_changed,false);assert.equal(r.real_pupil_data_used,false);assert.equal(r.production_quota_unchanged,true);assert.equal(r.unrelated_bindings_unchanged,true);assert.equal(r.runtime_unchanged,true);
 assert.equal(r.draft_content.lessons,410);assert.equal(r.draft_content.protocols,56);assert.equal(r.draft_content.hash_mismatches,0);assert.equal(r.persistence_evidence.only_owned_routes,true);assert.ok(r.persistence_evidence.usage.reduce((n,u)=>n+Number(u.chat_requests||0),0)<=60);
 for(const q of r.requests){assert.equal(q.generation_model_calls,0);assert.equal(q.generation_tokens,0)}
 for(const k of ['base_version','base_deployment','base_code_etag','candidate_code_etag','source_sha256','runtime_sha256','source_commit'])assert.equal(r[k],rs[0][k],k);assert.deepEqual(r.source_hashes,rs[0].source_hashes);
}
assert.notEqual(rs[0].synthetic_id,rs[1].synthetic_id);const checked=rs.flatMap(r=>r.new_lessons_checked);assert.deepEqual(checked.map(x=>x.lesson_id),build.new_ids);assert.equal(new Set(checked.map(x=>x.lesson_id)).size,40);
const requests=rs.flatMap((r,i)=>r.requests.map(x=>({...x,synthetic_group:i+1}))),t=requests.map(q=>q.round_trip_ms).sort((a,b)=>a-b);
const report={...rs.at(-1),requests,new_lessons_checked:checked,synthetic_id:undefined,synthetic_group:undefined,synthetic_identities_used:2,synthetic_cleanup:{ok:true,deleted:true,identities:2},group_evidence:rs.map(r=>({group:r.synthetic_group,requests:r.requests.length,candidate_version:r.candidate_version,cleanup_verified:r.synthetic_cleanup.deleted})),latency:{samples:t.length,p50_ms:t[Math.floor(t.length*.5)],p95_ms:t[Math.floor(t.length*.95)],max_ms:t.at(-1),includes_actual_supabase_auth_and_network:true,origin:'GitHub runner, not physical iPhone',transcription_and_tts_excluded:true},new_lessons:40,new_questions:120,previous_370_preserved:true,procedural_factory_unchanged:true,full_curriculum_complete:false,human_teacher_reviewed:false,verified_at:new Date().toISOString()};
assert.equal(requests.length,84);writeFileSync('content-410-private/report.json',JSON.stringify(report,null,2));console.log(JSON.stringify({phase:report.phase,lessons:410,new_lessons:40,requests:84,model_calls:0,synthetic_identities_deleted:2,production_changed:false}));
