// Canonical promotion only. Never publish temporary authentication/import fixtures.
import{readFileSync,writeFileSync,mkdirSync}from'node:fs';import{createHash}from'node:crypto';import{execFileSync}from'node:child_process';import assert from'node:assert/strict';
const script='coco-eterna-v159',url='https://coco-eterna-v159.chatinmobiliario.workers.dev',release='eterna-library-2026.09-v7-370-content-c26c61c',oldRelease='eterna-library-2026.09-v6-310-traceable-12c672';
const expectedMain='1c484e01e2e3f5cf67fc5ad4eeeb5374ac52f767',expectedBase='a632d0a8-7287-4521-b67d-23a422e8815e';
const proof=JSON.parse(readFileSync('.private-proof/report.json')),build=JSON.parse(readFileSync('.build-proof/report.json'));
assert.equal(proof.phase,'canonical-private-verified');assert.equal(proof.release,release);assert.equal(proof.base_version,expectedBase);assert.equal(proof.requests.length,181);assert.equal(proof.regressions_passed,906);assert.equal(build.tests_passed,906);assert.equal(build.tests_failed,0);
assert.equal(proof.synthetic_cleanup.ok,true);assert.equal(proof.synthetic_cleanup.deleted,true);assert.equal(proof.synthetic_cleanup.identities,4);assert.equal(proof.all_new_lessons_exercised,60);assert.equal(proof.nonrepeating_round_fix_preserved,true);
assert.equal(proof.draft_content.lessons,370);assert.equal(proof.draft_content.protocols,56);assert.equal(proof.draft_content.hash_mismatches,0);assert.equal(proof.real_pupil_data_used,false);assert.equal(proof.production_quota_unchanged,true);
assert.deepEqual(proof.new_lessons_tested.map(l=>l.lesson_id).sort(),[...build.added_ids].sort());for(const q of proof.requests){assert.equal(q.generation_model_calls,0);assert.equal(q.generation_tokens,0)}
const hash=v=>createHash('sha256').update(v).digest('hex');for(const[path,p]of Object.entries(proof.source_hashes))assert.equal(hash(readFileSync(path)),p.sha256,path);
assert.equal(hash(readFileSync('eterna-worker/src/index.js')),'0abc6e3e3b316974801331aec55b369d89dd78e2cf5ea982bdfc59943ca97d53');assert.equal(hash(readFileSync('eterna-worker/src/library/procedural-v1.js')),'371f32609b1b2c3d4ba50ab4f67a487629f6cc536ced031a583e4d0ca6e46d98');
const expectedCandidate=proof.candidate_version;assert.match(expectedCandidate,/^[a-f0-9-]{36}$/);assert.match(proof.candidate_url,/^https:\/\/[a-f0-9-]+-coco-eterna-v159\.chatinmobiliario\.workers\.dev$/);
const token=String(process.env.CLOUDFLARE_API_TOKEN||'').replace(/\s/g,''),account=String(process.env.CLOUDFLARE_ACCOUNT_INPUT||'').replace(/^https:\/\/dash.cloudflare.com\//,'').split('/')[0];assert.ok(token&&/^[a-f0-9]{32}$/i.test(account));console.log('::add-mask::'+token);console.log('::add-mask::'+account);
async function mainHead(){const r=await fetch('https://api.github.com/repos/diegopenn-png/coco-en-forma/git/ref/heads/main',{headers:{Authorization:'Bearer '+process.env.GH_TOKEN,Accept:'application/vnd.github+json'},signal:AbortSignal.timeout(25000)});assert.equal(r.status,200);return(await r.json()).object.sha}
async function cf(path){const r=await fetch(`https://api.cloudflare.com/client/v4/accounts/${account}/workers/scripts/${script}${path}`,{headers:{Authorization:'Bearer '+token},signal:AbortSignal.timeout(30000)});const p=await r.json();assert.ok(r.ok&&p.success!==false,'Cloudflare read failed '+r.status);return p.result}
async function live(){const p=await cf('/deployments'),d=(Array.isArray(p)?p:p.deployments)?.[0];assert.ok(d?.versions?.length===1&&d.versions[0].percentage===100);return d}
const canon=v=>Array.isArray(v)?v.map(canon):v&&typeof v==='object'?Object.fromEntries(Object.keys(v).sort().map(k=>[k,canon(v[k])])):v;
const fingerprint=v=>hash(JSON.stringify(canon(v))),reduced=v=>v.resources.bindings.filter(b=>b.name!=='ETERNA_LIBRARY_RELEASE').sort((a,b)=>a.name.localeCompare(b.name));
const baseline=await live();assert.equal(baseline.versions[0].version_id,expectedBase);assert.equal(baseline.id,proof.base_deployment);assert.equal(await mainHead(),expectedMain);
const old=await cf('/versions/'+expectedBase),candidate=await cf('/versions/'+expectedCandidate);assert.equal(old.resources.script.etag,proof.base_code_etag);assert.equal(candidate.resources.script.etag,proof.candidate_code_etag);
assert.equal(fingerprint(reduced(candidate)),fingerprint(reduced(old)),'Only the release label may change');assert.equal(fingerprint(candidate.resources.script_runtime),fingerprint(old.resources.script_runtime));
const vars=Object.fromEntries(candidate.resources.bindings.filter(b=>b.type==='plain_text').map(b=>[b.name,b.text]));assert.equal(vars.ETERNA_LIBRARY_RELEASE,release);assert.equal(vars.ENABLE_ETERNA_LIBRARY,'true');assert.equal(vars.ETERNA_EXERCISE_FACTORY,'v1');assert.equal(vars.ETERNA_CURRICULAR_COMPASS,'v1');
async function health(u,isNew){const r=await fetch(u+'/health',{headers:{'Cache-Control':'no-cache'},signal:AbortSignal.timeout(20000)});assert.equal(r.status,200);const h=await r.json();assert.equal(h.ok,true);assert.equal(h.owned_library.enabled,true);assert.equal(h.owned_library.release,isNew?release:oldRelease);assert.equal(h.owned_library.lessons,isNew?370:310);assert.equal(h.owned_library.protocols,56);assert.equal(h.owned_library.curriculum_complete,false);assert.equal(h.exercise_factory.enabled,true);assert.equal(h.exercise_factory.families,22);assert.equal(h.curricular_compass.enabled,true);assert.equal(h.curricular_compass.source_elements,9033);return h}
const configuration=h=>fingerprint({provider:h.ai_provider,models:h.model_configuration,features:h.features,supabase:h.supabase_configured,stripe:h.stripe_configured,openai:h.openai_configured,cloudflare:h.cloudflare_ai_configured});
async function denied(u){for(const path of ['/v1/chat','/v1/chat-job','/v1/transcribe']){const r=await fetch(u+path,{method:'POST',headers:{Origin:'https://cocoenforma.com'},signal:AbortSignal.timeout(20000)});assert.equal(r.status,401,path)}}
const before=await health(url,false),preview=await health(proof.candidate_url,true);assert.equal(configuration(before),configuration(preview));await denied(url);await denied(proof.candidate_url);
for(const b of candidate.resources.bindings)assert.ok(['plain_text','secret_text','ai'].includes(b.type));
const rt=candidate.resources.script_runtime||{},ai=candidate.resources.bindings.find(b=>b.type==='ai'),config={name:script,main:'src/index.js',compatibility_date:rt.compatibility_date,compatibility_flags:rt.compatibility_flags||[],vars};if(ai)config.ai={binding:ai.name};if(rt.limits?.cpu_ms)config.limits={cpu_ms:rt.limits.cpu_ms};if(rt.usage_model)config.usage_model=rt.usage_model;
writeFileSync('eterna-worker/.content370-publish.json',JSON.stringify(config));const dir='content-370-production-evidence';mkdirSync(dir,{recursive:true});
const report={phase:'pre-promotion',production_commit:expectedMain,release,base_version:expectedBase,candidate_version:expectedCandidate,source_sha256:proof.source_sha256,runtime_sha256:proof.runtime_sha256,content_sha256:proof.source_hashes['eterna-worker/src/library/content-v1.js'].sha256,canonical_etag:proof.candidate_code_etag,lessons:370,new_lessons:60,questions:1110,new_questions:180,protocols:56,counts_by_stage:build.counts_by_stage,tests_passed:906,tests_failed:0,actual_private_requests:181,all_new_lessons_exercised:60,private_zero_generation_tokens:true,private_latency:proof.latency,synthetic_identities_deleted:4,old_lesson_objects_preserved:310,old_question_ids_and_keys_preserved:930,no_repeat_round_fix_preserved:true,only_configuration_change:'ETERNA_LIBRARY_RELEASE',microphone_unchanged:true,frontend_unchanged:true,models_unchanged:true,quotas_unchanged:true,production_changed:false,full_curriculum_complete:false,human_teacher_reviewed:false};
const save=()=>writeFileSync(dir+'/report.json',JSON.stringify(report,null,2));save();
function deploy(id,message){try{execFileSync('npx',['wrangler','versions','deploy',id+'@100%','--name',script,'--config','.content370-publish.json','--message',message,'--yes'],{cwd:'eterna-worker',env:{...process.env,CLOUDFLARE_API_TOKEN:token,CLOUDFLARE_ACCOUNT_ID:account,CI:'true'},encoding:'utf8',timeout:180000,maxBuffer:8*1024*1024})}catch(e){throw Error('Controlled promotion failed '+e.status+'; confidential output omitted')}}
assert.equal((await live()).id,baseline.id);assert.equal(await mainHead(),expectedMain);let attempted=false;
try{attempted=true;deploy(expectedCandidate,'Activate exact verified 60-lesson addition; preserve all existing lessons, voice and no-repeat rounds');let current,passed=false;
 for(let i=0;i<6;i++){current=await live();if(current.versions[0].version_id===expectedCandidate){try{const h=await health(url,true);assert.equal(configuration(h),configuration(before));await denied(url);report.live_features={owned_library:h.owned_library,exercise_factory:h.exercise_factory,curricular_compass:h.curricular_compass};passed=true;break}catch{}}await new Promise(r=>setTimeout(r,5000))}
 assert.ok(passed,'Live checks failed');assert.equal(await mainHead(),expectedMain);report.phase='production-verified';report.production_changed=true;report.production_version=expectedCandidate;report.deployment_id=current.id;report.verified_at=new Date().toISOString();save();console.log(JSON.stringify(report));
}catch(e){report.phase='not-ready';report.error=String(e.message).slice(0,300);if(attempted){const d=await live();if(d.versions[0].version_id===expectedCandidate){deploy(expectedBase,'Rollback failed content-only 370 lesson activation');report.rollback_verified=(await live()).versions[0].version_id===expectedBase}else report.rollback_skipped_concurrent_change=true}save();throw e}
