// Guarded promotion of a canonical, already tested Worker version. No private QA wrapper is deployed.
import{readFileSync,writeFileSync,mkdirSync}from'node:fs';import{createHash}from'node:crypto';import{execFileSync}from'node:child_process';import assert from'node:assert/strict';
const script='coco-eterna-v159',production='https://coco-eterna-v159.chatinmobiliario.workers.dev',release='eterna-library-2026.09-v2-160',expectedBase='5da15a04-5396-4841-8b21-a94c0c6647c3';
const proof=JSON.parse(readFileSync('.private-proof/report.json'));
assert.equal(proof.phase,'canonical-private-verified');assert.equal(proof.release,release);assert.equal(proof.base_version,expectedBase);assert.equal(proof.requests.length,80);assert.equal(proof.synthetic_cleanup.ok,true);assert.equal(proof.synthetic_cleanup.deleted,true);assert.equal(proof.draft_content.lessons,160);assert.equal(proof.draft_content.protocols,40);assert.equal(proof.draft_content.hash_mismatches,0);assert.equal(proof.regressions_passed,512);assert.equal(proof.ui_scenarios,42);
for(const r of proof.requests){assert.equal(r.generation_model_calls,0);assert.equal(r.generation_tokens,0)}
const hash=x=>createHash('sha256').update(x).digest('hex');for(const[path,p]of Object.entries(proof.source_hashes))assert.equal(hash(readFileSync(path)),p.sha256,'Release source differs from private-tested bytes: '+path);
assert.ok(!readFileSync('eterna-worker/src/index.js','utf8').includes('__synthetic_library_qa'));
const expectedMain=String(process.env.EXPECTED_MAIN||'');assert.match(expectedMain,/^[a-f0-9]{40}$/);assert.equal(execFileSync('git',['rev-parse','HEAD:eterna-worker/src/index.js'],{encoding:'utf8'}).trim(),proof.source_hashes['eterna-worker/src/index.js'].sha);
const token=String(process.env.CLOUDFLARE_API_TOKEN||'').replace(/\s/g,''),account=String(process.env.CLOUDFLARE_ACCOUNT_INPUT||'').replace(/^https:\/\/dash.cloudflare.com\//,'').split('/')[0];assert.ok(token&&/^[a-f0-9]{32}$/i.test(account));console.log('::add-mask::'+token);console.log('::add-mask::'+account);
async function mainHead(){const r=await fetch('https://api.github.com/repos/diegopenn-png/coco-en-forma/git/ref/heads/main',{headers:{Authorization:'Bearer '+process.env.GH_TOKEN,Accept:'application/vnd.github+json'},signal:AbortSignal.timeout(25000)});assert.equal(r.status,200);return(await r.json()).object.sha}
async function cf(path){const r=await fetch(`https://api.cloudflare.com/client/v4/accounts/${account}/workers/scripts/${script}${path}`,{headers:{Authorization:'Bearer '+token},signal:AbortSignal.timeout(30000)});const p=await r.json();assert.ok(r.ok&&p.success!==false,'Cloudflare control read failed '+r.status);return p.result}
async function live(){const p=await cf('/deployments'),d=(Array.isArray(p)?p:p.deployments)?.[0];assert.ok(d?.versions?.length===1&&d.versions[0].percentage===100,'Expected one production version');return d}
function canon(v){return Array.isArray(v)?v.map(canon):v&&typeof v==='object'?Object.fromEntries(Object.keys(v).sort().map(k=>[k,canon(v[k])])):v}
function fingerprint(v){return hash(JSON.stringify(canon(v)))}
function bindings(v){return v.resources.bindings.filter(b=>b.name!=='ETERNA_LIBRARY_RELEASE').sort((a,b)=>a.name.localeCompare(b.name))}
const baseline=await live();assert.equal(baseline.versions[0].version_id,expectedBase,'Concurrent production change; stop');assert.equal(await mainHead(),expectedMain);
const old=await cf('/versions/'+expectedBase),candidate=await cf('/versions/'+proof.candidate_version);
assert.equal(old.resources.script.etag,proof.base_code_etag);assert.equal(candidate.resources.script.etag,proof.candidate_code_etag);assert.equal(fingerprint(bindings(candidate)),fingerprint(bindings(old)),'Unrelated bindings changed');assert.equal(fingerprint(candidate.resources.script_runtime),fingerprint(old.resources.script_runtime),'Runtime changed');
const vars=Object.fromEntries(candidate.resources.bindings.filter(b=>b.type==='plain_text').map(b=>[b.name,b.text]));assert.equal(vars.ENABLE_ETERNA_LIBRARY,'true');assert.equal(vars.ETERNA_LIBRARY_RELEASE,release);
async function health(url,wantNew){const r=await fetch(url+'/health',{signal:AbortSignal.timeout(20000)});assert.equal(r.status,200);const p=await r.json();assert.equal(p.ok,true);assert.equal(p.owned_library?.enabled,true);assert.equal(p.owned_library.release,wantNew?release:'eterna-library-2026.09-v1');assert.equal(p.owned_library.lessons,wantNew?160:80);assert.equal(p.owned_library.protocols,wantNew?40:24);assert.equal(p.owned_library.curriculum_complete,false);return p}
function configFingerprint(p){return fingerprint({provider:p.ai_provider,models:p.model_configuration,features:p.features,supabase:p.supabase_configured,stripe:p.stripe_configured,openai:p.openai_configured,cloudflare:p.cloudflare_ai_configured})}
async function denied(url){for(const path of ['/v1/chat','/v1/chat-job','/v1/transcribe']){const r=await fetch(url+path,{method:'POST',headers:{Origin:'https://cocoenforma.com'},signal:AbortSignal.timeout(20000)});assert.equal(r.status,401,'Unauthorized route must remain blocked '+path)}}
const oldHealth=await health(production,false),candidateHealth=await health(proof.candidate_url,true);assert.equal(configFingerprint(oldHealth),configFingerprint(candidateHealth));await denied(production);await denied(proof.candidate_url);
for(const b of candidate.resources.bindings)assert.ok(['plain_text','secret_text','ai'].includes(b.type),'Unmapped binding; do not proceed');
const rt=candidate.resources.script_runtime||{},ai=candidate.resources.bindings.find(b=>b.type==='ai'),config={name:script,main:'src/index.js',compatibility_date:rt.compatibility_date,compatibility_flags:rt.compatibility_flags||[],vars};if(ai)config.ai={binding:ai.name};if(rt.limits?.cpu_ms)config.limits={cpu_ms:rt.limits.cpu_ms};
writeFileSync('eterna-worker/.library-v2-production.json',JSON.stringify(config));mkdirSync('library-v2-production-evidence',{recursive:true});
const report={phase:'pre-promotion',release,production_commit:expectedMain,base_version:expectedBase,candidate_version:proof.candidate_version,source_sha256:proof.source_sha256,runtime_sha256:proof.runtime_sha256,content_sha256:proof.source_hashes['eterna-worker/src/library/content-v1.js'].sha256,lessons:160,new_lessons:80,questions:480,new_questions:240,protocols:40,new_protocols:16,tests_passed:512,ui_scenarios:42,real_authenticated_private_requests:80,private_latency:proof.latency,private_zero_generation_tokens:true,temporary_identity_deleted:true,models_unchanged:true,unrelated_bindings_unchanged:true,runtime_unchanged:true,microphone_unchanged:true,frontend_unchanged:true,production_changed:false,full_curriculum_complete:false};
const save=()=>writeFileSync('library-v2-production-evidence/report.json',JSON.stringify(report,null,2));save();
function deploy(id,message){try{execFileSync('npx',['wrangler','versions','deploy',id+'@100%','--name',script,'--config','.library-v2-production.json','--message',message,'--yes'],{cwd:'eterna-worker',env:{...process.env,CLOUDFLARE_API_TOKEN:token,CLOUDFLARE_ACCOUNT_ID:account,CI:'true'},encoding:'utf8',timeout:180000,maxBuffer:8*1024*1024})}catch(e){throw Error('Controlled deployment command failed '+e.status+'; confidential output withheld')}}
assert.equal((await live()).id,baseline.id);assert.equal(await mainHead(),expectedMain);let attempted=false;
try{
 attempted=true;deploy(proof.candidate_version,'Activate exact tested 160-lesson / 40-protocol library; microphone and provider unchanged');
 let current,passed=false;
 for(let i=0;i<6;i++){current=await live();if(current.versions[0].version_id===proof.candidate_version){try{assert.equal(configFingerprint(await health(production,true)),configFingerprint(oldHealth));await denied(production);passed=true;break}catch{}}await new Promise(r=>setTimeout(r,5000))}
 assert.ok(passed,'Production checks failed');assert.equal(await mainHead(),expectedMain);
 report.phase='production-verified';report.production_changed=true;report.production_version=proof.candidate_version;report.deployment_id=current.id;report.verified_at=new Date().toISOString();save();console.log(JSON.stringify(report));
}catch(e){report.phase='not-ready';report.error=String(e.message).slice(0,300);if(attempted){const current=await live();if(current.versions[0].version_id===proof.candidate_version){deploy(expectedBase,'Rollback failed 160-lesson content promotion');report.rollback_verified=(await live()).versions[0].version_id===expectedBase}else report.rollback_skipped_concurrent_change=true}save();throw e}
